### ISSUE TITLE
Snowpeak Ruins checklist text overlap

### ISSUE THREAD

**Issue by Apheayenne** [AudioPixie/TPRTracker#44]
**Describe the bug**
1) On the Snowpeak Ruins checklist, the "Courtyard Central Check" and "Ball and Chain" text are overlapping.
2) On the Castle Town checklist, the "Malo Mart Magic Armor" and "Charlo Donation Blessing" text are overlapping

**Screenshots**
![image](https://github.com/AudioPixie/TPRTracker/assets/78513012/6abb0f9f-413a-4d7c-a12e-c8e37107dd76)
![image](https://github.com/AudioPixie/TPRTracker/assets/78513012/d1b44912-56c5-4e63-974f-6978781a7e54)

**Additional context**

**Comment by AudioPixie** [comment]
Noticed this in a few places, seems to only happen when the window is a certain size. Goes away when window is resized smaller. These lists have been causing issues, might rework them to not use Unity's listing system and redo it manually since it's a bit temperamental.

**Comment by Apheayenne** [comment]
Im wondering if it caused by the automatic wrapping. like it looks like the text will fit, but the program will wrap it automatically. i think it worked if the window was maximized.

**Comment by AudioPixie** [comment]
The text wraps automatically, but that changes the height of the text object to be larger, which is what is supposed to be taken into account when listing them. It's like it sometimes does the wrapping first, but sometimes does the listing first... kinda weird

**Comment by AudioPixie** [comment]
Reworked the checks so that the automatic height is working. Moved the TMP_Text component to the same level as the toggle so that it isn't nested anymore
