### ISSUE TITLE
Fix sky character counter

### ISSUE THREAD

**Issue by AudioPixie** [AudioPixie/TPRTracker#47]
Should ask in the discord what people prefer, but could help with confusion that it's sky book plus 6 characters, but the counter is from 1-7. Could change it to start at 0, or separate out book and characters

**Comment by SadieDragon** [comment]
My personal vote here is 0-6, if anything. That was your tl'dr for this.

Separation adds more icons to be tracked. We already have this with Illia's Charm and the Horse Call; these items are one and the same, but Illia's Charm becomes the Horse Call (and is the only way to obtain it) if you don't start with it.

The only concern I have with starting at 0 is new players still not understanding "But I clicked on this, why is it 0? I have 1!" but I don't really know how to address that.

**Comment by AudioPixie** [comment]
Changed it so it starts at 0, but it says "B" instead for book. So it goes B, 1, 2, 3, 4, 5, 6. Think this is a happy medium that will reduce the most confusion
