### ISSUE TITLE
Add Hover Text to Items

### ISSUE THREAD

**Issue by Kemui52** [AudioPixie/TPRTracker#72]
Something helpful for those not super-familiar with TP's items would be if the item names would appear when you hover over the item. This tracker has been very helpful to me since I decided to play a rando of a game I've not touched in ten years, but one of the more confusing parts of the experience has been trying to identify what some of the quest and color-coded items are. I've figured most things out by ticking them on and off to see what checks they enable, but some things like the scents and the overworld keys I had to take a night's sleep to think of the meaning behind the icon.

By now, I'm almost finished with the run and deduced what everything means (except the blue letter), but I don't expect myself to remember all of them for round two. A text label when hovering over an item would be the clearest way to identify any icon.

**Comment by AudioPixie** [comment]
Added this feature. It can be turned off in visual settings. Is automatically turned off when you click "apply race settings"
