### ISSUE TITLE
Lakebed Tempale 3rd Small Key Checks

### ISSUE THREAD

**Issue by CCLRguy2012** [AudioPixie/TPRTracker#80]
When i have 2 small keys set as collected it only shows the checks up to the east water supply area. when having two keys lets you turn on the water where 3 keys is only required to get into the miniboss i have key sanity collected if that helps?

**Comment by AudioPixie** [comment]
Hi there! This is working as intended. 

While yes, you can access deku toad etc. with only 2 small keys, the player can theoretically use those 2 keys on the wrong doors with no way to recover them. This could softlock the game making it unbeatable if you used your keys wrong, so for this reason checks in this situation are out-of-logic until you have 3 keys. 

There are a few instances in dungeons where you logically need "extra" keys for certain checks, iirc Snowpeak can be fully cleared on 2 small keys if you do everything right, but on the logic side the randomizer assumes the player makes the absolute worst decisions possible with their keys. This way there's no chance of softlocking yourself, but there are no issues doing these checks out of logic if you know what you're doing.

Hope this helps, thanks!
